config/routes.rb
Rails.application.routes.draw do
  resources :tests

  get 'main/index'

  root 'main#index'

  resources :vacancies

  resources :users

  resources :organizations

end

app/models/organization.rb
class Organization
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :description, type: String
  field :geo, type: Hash, default: {country:"", city:"", coords:[0,0]}
  field :website, type: String
  field :email, type: String

  has_many :vacancies, dependent: :delete
  accepts_nested_attributes_for :vacancies
  #field :administrated_by, type: Moped::BSON::ObjectId
end

app/models/test.rb
class Test
  include Mongoid::Document
  field :name, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :employed_by, type: String

end

app/models/vacancy.rb
class Vacancy
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic

  field :name, type: String
  field :salary, type: String
  field :description, type: String
  field :requires, type: String
  field :conditions, type: String

  #field :employer, type: Moped::BSON::ObjectId
  belongs_to :organization, dependent: :nullify
end

app/controllers/application_controller.rb
#class ApplicationController < InheritedResources::Base
class ApplicationController < ActionController::Base
   inherit_resources
   actions :all#, :except => [ :destroy]
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  skip_before_filter :verify_authenticity_token

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)
    #@project.something_special!
    create!
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update

    #@organization = Organization.update(organization_params)
    #@project.something_special!
    update!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      #geo hash dont work:
      #params.require(:organization).permit(:name, :description, :geo, :website, :email, :administrated_by)
      #all params, include hash types, are working:
      params.require(:organization).permit!
      #custom params: http://goo.gl/OeIwah
    end
end





















  # # GET /organizations/new
  # def new
  #   @organization = Organization.new
  # end

  # # GET /organizations/1/edit
  # def edit
  # end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  skip_before_filter :verify_authenticity_token

  # GET /vacancies
  # GET /vacancies.json
  def index
    @vacancies = Vacancy.all
  end

  # GET /vacancies/1
  # GET /vacancies/1.json
  def show
  end

  # POST /vacancies
  # POST /vacancies.json
  def create
    @vacancy = Vacancy.new(vacancy_params)
    #@project.something_special!
    create!
  end

  # PATCH/PUT /vacancies/1
  # PATCH/PUT /vacancies/1.json
  def update

    #@vacancy.organization = Organization.first
    #@vacancy = Vacancy.update(vacancy_params)
    #@project.something_special!
    update!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacancy_params
      params.require(:vacancy).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Mega Work Searcher</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script>
    FileAPI = {
      jsUrl: 'libs/angular/FileAPI.min.js',
      flashUrl: 'libs/angular/FileAPI.flash.swf'
    };
  </script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="progress middle hide">
    <div class="progress-bar progress-bar-striped active" role="progressbar" style="width: 100%">
    </div>
  </div>
  <div id="mainContent" class="" style="padding-top:40px">
    <%= yield %>
  </div>
</body>
</html>

app/views/main/index.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
   <div class="container">
     <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Mega Work Searcher</a>
      </div>
      <div class="navbar-collapse collapse">
         <ul class="nav navbar-nav">
            <li>
               <a href="" class="dropdown-toggle" data-toggle="dropdown">
                  Админка<b class="caret"></b>
               </a>
               <ul class="dropdown-menu nav navbar-inverse" role="menu">
                  <li><a href="#/organization/settings">Компания</a></li>
                  <li><a href="#/person/settings">Сотрудник</a></li>
               </ul>
            </li>
         </ul>
         <form action="/Account/LogOff" class="navbar-right" id="logoutForm" method="post">
            <ul class="nav navbar-nav navbar-right">
               <li>
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Войти<b class="caret"></b>
                 </a>
                  <ul class="dropdown-menu nav navbar-inverse">
                     <li>
                       <a href="#" title="Управление">ВКонтакте</a>
                     </li>
                     <li>
                       <a href="#">Facebook</a>
                     </li>
                  </ul>
               </li>
               <li>
                  <a href="" class="dropdown-toggle" data-toggle="dropdown">Регистрация<b class="caret"></b></a>
                  <ul class="dropdown-menu nav navbar-inverse" role="menu">
                     <li>
                        <a href="#/organization/register">Компания</a>
                     </li>
                     <li>
                        <a href="#/person/register">Сотрудник</a>
                     </li>
                  </ul>
               </li>
            </ul>
         </form>
      </div>
   </div>
</div>

<div class="container body-content" ui-view></div>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Website</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.email %></td>
        <td><%= organization.website %></td>
        <td><%= organization.description %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @organization.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @organization.website %>
</p>

<p>
  <strong>Description:</strong>
  <pre><%= @organization.description %></pre>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/vacancies/_form.html.erb
<%= form_for(@vacancy) do |f| %>
  <% if @vacancy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

      <ul>
      <% @vacancy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :requires %><br>
    <%= f.text_area :requires %>
  </div>
  <div class="field">
    <%= f.label :conditions %><br>
    <%= f.text_area :conditions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vacancies/edit.html.erb
<h1>Editing vacancy</h1>

<%= render 'form' %>

<%= link_to 'Show', @vacancy %> |
<%= link_to 'Back', vacancies_path %>

app/views/vacancies/index.html.erb
<h1>Listing vacancies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacancies.each do |vacancy| %>
      <tr>
        <td><%= link_to 'Show', vacancy %></td>
        <td><%= link_to 'Edit', edit_vacancy_path(vacancy) %></td>
        <td><%= link_to 'Destroy', vacancy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vacancy', new_vacancy_path %>

app/views/vacancies/new.html.erb
<h1>New vacancy</h1>

<%= render 'form' %>

<%= link_to 'Back', vacancies_path %>

app/views/vacancies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_vacancy_path(@vacancy) %> |
<%= link_to 'Back', vacancies_path %>